---
delimiters:
    - "__"
constantDelimiters:
    - "$$"
skipDelimiters:
    - "//##"
ignore:
    - "config.yml"
    - ".DS_Store"
    - ".git"
    - "node_modules"
    - ".env"
    - "artifacts"
    - "cache"
    - "typechain"
rootDirectoryName: "$$project root directory name$$"